{
 "title": "Load Test",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "HarperDB Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "harperdb_process_cpu_utilization",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes / memory_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Transaction Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "rate(harperdb_database_txns_total{database=\"ci\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration (p95)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "duration{path=\"insert\", quantile=\"0.95\"}",
     "legendFormat": "insert"
    },
    {
     "expr": "duration{path=\"search_by_conditions\", quantile=\"0.95\"}",
     "legendFormat": "search-by-condition"
    },
    {
     "expr": "duration{path=\"search_by_value\", quantile=\"0.95\"}",
     "legendFormat": "search-by-value"
    }
   ]
  },
  {
   "title": "DB Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "rate(harperdb_database_puts_total{database=\"ci\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer (p95)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transfer{path=\"search_by_conditions\", quantile=\"0.95\"}",
     "legendFormat": "search-by-condition"
    },
    {
     "expr": "transfer{path=\"search_by_value\", quantile=\"0.95\"}",
     "legendFormat": "search-by-value"
    }
   ]
  },
  { "title": "K6 Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "sql-analytics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{testid=\"sql-analytics\"}",
     "legendFormat": "request duration (p99)"
    },
    {
     "expr": "k6_http_req_failed_rate{testid=\"sql-analytics\"}",
     "legendFormat": "fail rate"
    },
    {
     "expr": "k6_http_reqs_total{testid=\"sql-analytics\"}",
     "legendFormat": "total requests"
    }
   ]
  },
  {
   "title": "insert",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{testid=\"insert\"}",
     "legendFormat": "request duration (p99)"
    },
    {
     "expr": "k6_http_req_failed_rate{testid=\"insert\"}",
     "legendFormat": "fail rate"
    },
    {
     "expr": "k6_http_reqs_total{testid=\"insert\"}",
     "legendFormat": "total requests"
    }
   ]
  },
  {
   "title": "search-by-conditions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{testid=\"search-by-conditions\"}",
     "legendFormat": "request duration (p99)"
    },
    {
     "expr": "k6_http_req_failed_rate{testid=\"search-by-conditions\"}",
     "legendFormat": "fail rate"
    },
    {
     "expr": "k6_http_reqs_total{testid=\"search-by-conditions\"}",
     "legendFormat": "total requests"
    }
   ]
  },
  {
   "title": "search-by-value-wildcard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99{testid=\"search-by-value-wildcard\"}",
     "legendFormat": "request duration (p99)"
    },
    {
     "expr": "k6_http_req_failed_rate{testid=\"search-by-value-wildcard\"}",
     "legendFormat": "fail rate"
    },
    {
     "expr": "k6_http_reqs_total{testid=\"search-by-value-wildcard\"}",
     "legendFormat": "total requests"
    }
   ]
  },
  { "title": "Docker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "docker_container_cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "docker_container_memory_percent",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}