global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'harperdb'
    metrics_path: "/prometheus_exporter/metrics"
    static_configs:
      - targets: ['harperdb:9926']
    scheme: https
    tls_config:
      insecure_skip_verify: true
      ca_file: ""
      cert_file: ""
      key_file: ""
      server_name: ""