services:
  harperdb:
    image: harperdb/harperdb:latest
    container_name: harperdb
    ports:
      - "9925:9925"
      - "9926:9926"
    volumes:
      - ./test-data:/home/harperdb/tmpdata
      - harperdb:/home/harperdb/hdb
    environment:
      - HDB_ADMIN_USERNAME=harperdb
      # this is an ephemeral instance running in ci with dummy data,
      # no need to treat password sensitively. however, for demo purposes
      # we shall "keep it secret, keep it safe"
#      - HDB_ADMIN_PASSWORD
      - HDB_ADMIN_PASSWORD=test
      - NODE_ENV=dev

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - '--enable-feature=remote-write-receiver'
      - '--web.enable-remote-write-receiver'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./configs/grafana.yaml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./configs/dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./configs/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"

  renderer:
    container_name: renderer
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8081:8081"

volumes:
  harperdb:
  grafana: