services:
  harperdb:
    image: harperdb/harperdb:latest
    ports:
      - "9925:9925"
      - "9926:9926"
    environment:
      - HDB_ADMIN_USERNAME=harperdb_ci
      # this is an ephemeral instance running in ci with dummy data,
      # no need to treat password sensitively. however, for demo purposes
      # we shall "keep it secret, keep it safe"
#      - HDB_ADMIN_PASSWORD
      - HDB_ADMIN_PASSWORD=test
#      - LOG_LEVEL=debug
#      - CUSTOM_ENV=dev
      - NODE_ENV=dev