services:
  harperdb:
    image: harperdb/harperdb:latest
    ports:
      - "9925:9925"
      - "9926:9926"
    volumes:
      - ../data:/home/harperdb/tmpdata
    environment:
      - HDB_ADMIN_USERNAME=harperdb
      # this is an ephemeral instance running in ci with dummy data,
      # no need to treat password sensitively. however, for demo purposes
      # we shall "keep it secret, keep it safe"
#      - HDB_ADMIN_PASSWORD
      - HDB_ADMIN_PASSWORD=test
      - NODE_ENV=dev