name: harperdb-test

on: [workflow_dispatch]

jobs:
  harperdb-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup docker compose
        uses: docker/setup-compose-action@v1

      - name: start harperdb
        run: docker compose -f docker/harperdb-ci-compose.yaml up -d

      - name: wait for harperdb
        run: bash scripts/wait-for-harperdb.sh
        timeout-minutes: 1

      - name: load test data
        run: bash scripts/load-data.sh
        timeout-minutes: 1